export const PRODUCT_PAGE = {
    ADD_PRODUCTS: 'PRODUCT_PAGE_ADD_PRODUCTS',
    SET_CURRENT_PAGE: 'PRODUCT_PAGE_SET_CURRENT_PAGE',
    SET_PAGE_COUNT: 'PRODUCT_PAGE_SET_PAGE_COUNT'
}

export const CART = {
    ADD_ITEM: 'CART_ADD_ITEM',
    REMOVE_ITEM: 'CART_REMOVE_ITEM'
}
