export const MAIN_SET_COUNTER = 'MAIN_SET_COUNTER'

export const PRODUCT_PAGE_ADD_PRODUCTS = 'PRODUCT_PAGE_ADD_PRODUCTS'
export const PRODUCT_PAGE_SET_PAGE_NR = 'PRODUCT_PAGE_SET_PAGE_NR'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
